languages = \
{
	"english": {
		"self": "english",
		"": "",
		"Last Name": "Last Name",
		"First Name": "First Name",
		"Chinese Name": "Chinese Name",
		"School Location": "School Location",
		"Barcode": "Barcode",
		"Old Student ID": "Old Student ID",
		"Date of Birth": "Date of Birth",
		"Age": "Age",
		"Gender": "Gender",
		"Parent Name": "Parent Name",
		"Home Phone": "Home Phone",
		"Cell Phone": "Cell Phone",
		"Cell Phone 2": "Cell Phone 2",
		"Pick up Person": "Pick up Person",
		"Address": "Address",
		"State": "State",
		"City": "City",
		"Zipcode": "Zipcode",
		"Weekday/Weekend": "Weekday/Weekend",
		"Tuition Paid Day": "Tuition Paid Day",
		"Payment Method": "Payment Method",
		"Tuition Pay Amount": "Payment Amount",
		"E-mail": "E-mail",
		"Service Type": "Service Type",
		"Classes Awarded": "Classes Awarded",
		"Classes Remaining": "Classes Remaining",
		"Date": "Date",
		"Check-In Time": "Check-In Time",
		"Class Time": "Class Time",
		"How did you hear about the school?": "How did you hear\nabout this school?",
		"Notes": "Notes",
		"No student": "\nStudent was not found!\nType in the correct name or \n contact your system administrator.",
		"Con student": "\nAre you sure you would like\nto add this to the Database?",
		"Con S student": "\nAre you sure you would like\nto save this student's information to the Database?",
		"Ase student": "\nStudent with this barcode exists in the database\nAdding this student will overwrite the existing student.\nOverwrite current student?\n",
		"Sa student": "\nStudent has been added to the database.",
		"Cs student": "\nCheck in the student?\n",
		"ok": "    Ok    ",
		"yes": "    Yes    ",
		"no": "    No    ",
		"impdb": "Import Database",
		"expdb": "Export Database",
		"impxls": "Import from Excel",
		"impt": "Import Time Data",
		"imptxls": "Import from Excel",
		"expxls": "Export to Excel",
		"curfile": "Current Database File",
		"browse": "Browse",
		"browsephoto": "Select Picture",
		"filepath": "File Path",
		"Back": "Back",
		"Next": "Next",
		"saveto": "Save To",
		"Save": "Save",
		"choosedb": "Choose Database",
		"changelanguage": "中文语言显示",
		"awardclass": "Award Classes",
		"awardoneclass": "Single (+1)",
		"awardaddclass": "Award Additional Classes",
		"addstudent": "Add Student to Database",
		"Add Students": "Add Students", #students* for buttons
		"Scan Students": "Scan Students",
		"Student Database": "Student Database",
		"Tools": "Database Management",
		"Back to Main Menu": "Back to Main Menu",
		"Exit": "Exit",
		"Search": "Search",
		"cinstudent": "Check-In Student",
		"Search By": "Search By",
		"savestudent": "Save Student to Database",
		"Database succesfully updated!": "Database succesfully updated!\n",
		"File could not be imported": "File could not be imported\n",
		"Cancel": "Cancel",
		"Please choose a file": "Please choose a file\n",
		"spec": "",
		"Classes remaining for this student": "Classes remaining for this student",
		"gold60": "Gold (+60)",
		"basic15": "Basic (+15)",
		"Ret to Main": "Return to main window?",
		"Auto": "Auto",
		"Manual": "Manual",
		"close": "Close",
		"Amount Owed": "Amount Owed",
		">> Next 30 >>": ">> Next 30 >>",
		"<< Previous 30 <<": "<< Previous 30 <<",
		"Import succesful": "Import succesful",
		"Students imported: ": "Students imported: ",
		"Attendance data imported: ": "Attendance data imported: "
		},

	"chinese": {
		"self": "chinese",
		"First Name": "名",
		"Last Name": "姓",
		"Chinese Name": "中国名字",
		"School Location": "学校位置",
		"Barcode": "条码号",
		"Old Student ID": "旧学号",
		"Date of Birth": "出生日期",
		"Age": "年龄",
		"Gender": "性别",
		"Parent Name": "家长姓名",
		"Home Phone": "家庭电话",
		"Cell Phone": "手机",
		"Cell Phone 2": "手机 2",
		"Pick up Person": "学生接人",
		"Address": "住址",
		"State": "州",
		"City": "城市",
		"Zipcode": "邮政编码",
		"Weekday/Weekend": "平日/周末",
		"Tuition Paid Day": "支付学费日期",
		"Payment Method": "付款方式",
		"Tuition Pay Amount": "付款金额",
		"E-mail": "电子邮件",
		"Service Type": "课程级别",
		"Classes Awarded": "加入学生课程",
		"Classes Remaining": "剩余的类",
		"Date": "日期",
		"Check-In Time": "记录时间",
		"Class Time": "课程时间段",
		"How did you hear about the school?": "你是怎么找到我们学校?",
		"Notes": "笔记",
		"No student": "\n找不到的学生 ！\n键入正确的名称或与系统管理员联系。\n",
		"Con student": "\n确实要将向数据库中添加这吗?",
		"Ase student": "\n这个条码的学生存在于数据库中。\n添加这个学生将会覆盖现有的学生。\n覆盖当前的学生吗?\n",
		"Sa student": "\n已将学生添加到数据库中。",
		"Cs student": "\n你想要记录这个学生？\n",
		"ok": "    还行    ",
		"yes": "    确认    ",
		"no": "    不记录    ",
		"changelanguage": "English Language Display",
		"awardclass": "奖类",
		"awardoneclass": "奖一类",
		"awardaddclass": "奖其他类",
		"browse": "浏览",
		"browsephoto": "浏览照片",
		"addstudent": "向数据库中添加学生",
		"Add Students": "添加学生", #students* for buttons
		"Scan Students": "扫描的学生",
		"Save": "保存",
		"Student Database": "学生数据库",
		"Tools": "工具",
		"Back to Main Menu": "返回到主菜单",
		"Exit": "退出",
		"Next": "下一次",
		"Back": "返回",
		"Search": "搜索",
		"Search By": "通过搜索",
		"cinstudent": "记录这名学生",
		"savestudent": "将学生保存到数据库",
		"Database succesfully updated!": "数据库成功更新 ！\n",
		"File could not be imported": "不能导入文件\n",
		"Cancel": "取消",
		"Please choose a file": "请选择一个文件\n",
		"impdb": "导入数据库",
		"expdb": "导出数据库",
		"impxls": "从 excel 中导入",
		"impt": "导入时间数据",
		"imptxls": "从 excel 中导入",
		"expxls": "导出到 excel 中",
		"curfile": "当前数据库文件",
		"choosedb": "选择数据库",
		"": "",
		"Classes remaining for this student": "剩余的这名学生的班",
		"spec": "",
		"gold60": "黄金 (+60)",
		"basic15": "基本 (+15)",
		"Ret to Main": "返回到主屏幕吗？",
		"Auto": "Auto",
		"Manual": "Manual",
		"Con S student": "确实要将此学生的信息保存到数据库吗？",
		"close": "关闭",
		"Amount Owed": "所欠的金额",
		">> Next 30 >>": ">> Next 30 >>",
		"<< Previous 30 <<": "<< Previous 30 <<",
		"Import succesful": "Import succesful",
		"Students imported: ": "Students imported: ",
		"Attendance data imported: ": "Attendance data imported: "
	}
		
}

#try:
#	int('s')
#except ValueError:
#	print('s is not an int')

#print([n for n in range(2, 3)])