languages = \
{
	"english": {
		"self": "english",
		"": "",
		"Last Name": "Last Name",
		"First Name": "First Name",
		"Chinese Name": "Chinese Name",
		"School Location": "School Location",
		"Barcode": "Barcode",
		"Old Student ID": "Old Student ID",
		"Date of Birth": "Date of Birth",
		"Age": "Age",
		"Gender": "Gender",
		"Parent Name": "Parent Name",
		"Home Phone": "Home Phone",
		"Cell Phone": "Cell Phone",
		"Cell Phone 2": "Cell Phone 2",
		"Pick up Person": "Pick up Person",
		"Address": "Address",
		"State": "State",
		"City": "City",
		"Zipcode": "Zipcode",
		"Weekday/Weekend": "Weekday/Weekend",
		"Tuition Paid Day": "Tuition Paid Day",
		"Payment Method": "Payment Method",
		"Tuition Pay Amount": "Total Amount",
		"E-mail": "E-mail",
		"Service Type": "Service Type",
		"Classes Awarded": "Classes Awarded",
		"Classes Remaining": "Classes Remaining",
		"Date": "Date",
		"Check-In Time": "Check-In Time",
		"Class Time": "Class Time",
		"How did you hear about the school?": "How did you hear\nabout this school?",
		"Notes": "Notes",
		"No student": "\nStudent was not found!\nType in the correct name or\ncontact your system administrator.",
		"Con student": "\nAre you sure you would like\nto add this to the Database?",
		"Con S student": "\nAre you sure you would like\nto save this student's information to the Database?",
		"Ase student": "\nStudent with this barcode exists in the database\nAdding this student will overwrite the existing student.\nOverwrite current student?",
		"Sa student": "\nStudent has been added to the database.",
		"Cs student": "\nCheck in the student?",
		"No classes": "\nStudent does not have any more classes!",
		"ok": "    Ok    ",
		"yes": "    Yes    ",
		"no": "    No    ",
		"impdb": "Import Database",
		"expdb": "Export Database",
		"impxls": "Import from Excel",
		"impt": "Import Time Data",
		"imptxls": "Import Time Data from Excel",
		"expxls": "Export Database",
		"curfile": "Current Database File",
		"browse": "Browse",
		"browsephoto": "Select Picture",
		"filepath": "File Path",
		"Back": "Back",
		"Next": "Next",
		"saveto": "Save To",
		"Save": "Save",
		"choosedb": "Choose Database",
		"changelanguage": "中文显示",
		"awardclass": "Award Classes",
		"awardoneclass": "Single (+1)",
		"awardaddclass": "Award Additional Classes",
		"addstudent": "Add Student to Database",
		"Add Students": "Add Students", #students* for buttons
		"Scan Students": "Scan Students",
		"Student Database": "Student Database",
		"Tools": "Database Management",
		"Back to Main Menu": "Back to Main Menu",
		"Exit": "Exit",
		"Search": "Search",
		"cinstudent": "Check-In Student",
		"Search By": "Search By",
		"savestudent": "Save Student to Database",
		"Database succesfully updated!": "Database succesfully updated!",
		"File could not be imported": "File could not be imported",
		"Cancel": "Cancel",
		"Please choose a file": "\nPlease choose a file",
		"spec": "",
		"Classes remaining for this student": "Classes remaining for this student",
		"gold60": "Gold (+60)",
		"basic15": "Basic (+15)",
		"Ret to Main": "Return to main window without saving?",
		"Scan": "Scan",
		"Manual": "Manual",
		"close": "Close",
		"Amount Owed": "Amount Owed",
		">> Next 30 >>": "Next",
		"<< Previous 30 <<": "Previous",
		">>> Last Page >>>": "Last Page",
		"Import succesful": "Import succesful",
		"Students imported: ": "Students imported: ",
		"Attendance data imported: ": "Attendance imported: ",
		"Student information": "Student information",
		"Address information": "Address",
		"Contact information": "Contact",
		"Payment information": "Payment",
		"Class time": "Class time",
		"Renew classes": "Renew classes",
		"Number of classes": "Classes to add",
		"Membership Expired": "Membership Expired",
		"Card Printed": "Card Printed",
		"Already Paid": "Already Paid",
		"Phone Number": "Phone Number",
		"RYB Student Management" : "RYB Student Management",
		"print report": "Print Report",
		"sdate": "Search Date",
		"Select Folder": "Select Folder",
		"Cash": "Cash",
		"Check": "Check",
		"Check Number": "Check Number",
		"Add Payment": "Add Payment",
		"Phone Number": "Phone Number",
		"RYB Student Management" : "RYB Student Management",
		"print report": "Print Report",
		"sdate": "Search Date",
		"Select Folder": "Select Folder",
		"salrep": "Salary Report",
		"print to file": "Make Report",
		"today's date": "Today's date",
		"last payment": "Last Payment",
		"dollar per hour": "Dollars per hour",
		"Hour": "Hour",
		"Minute": "Minute",
		"AM/PM": "AM/PM",
		"Print All": "Print All",
		"Confirm Time": "Confirm Time",
		"Confirm": "Confirm",
		"25s": " 25s",
		"50s": " 50s",
		"100s": " 100s",
		"set": "Set",
		"reset": "Reset",
		"resetcheckin": "Reset Check-In",
		"Confirm Reset": "Confirm Reset",
		"Early Check-ins have been reset": "Early Check-ins have been reset",
		"Yes, use current time": "Yes, use current time",
		"Yes, enter time": "Yes, enter time",
		"Brooklyn": "Brooklyn",
		"Chinatown": "Chinatown",
		"Elmhurst": "Elmhurst",
		"Flushing": "Flushing",
		"Choose School": "Choose School",
		"Print Successful": "Print Successful",
		"Early Check-in": "Early Check-in",
		"max hours": "Maximum Hours",
		"Choose PW File": "Choose PW File",
		"Create PW File": "Create PW File",
		"Create new Database": "Create new Database",
		"Convert to Encrypted DB": "Convert to Encrypted DB",
		"no_pw_set_pw": "Password must be reset.\nPlease enter the old password\nfollowed by the new password",
		"Enter Password": "Enter Password",
		"Reset DB Manager PW": "Reset DB Manager PW",
		"confirmed reset": "Password has been reset!",
		"wrong password try again": "You have entered the wrong password, try again!",
		"Choose Maker File": "Choose Maker File",
		"Create new Markerfile": "Create new Markerfile",
		"Database Backup Successful": "Database Backup Successful",
		"Student Information": "Student Information",
		"Attendance Table": "Attendance Table"
		},

	"chinese": {
		"self": "chinese",
		"First Name": "    名    ",
		"Last Name": "    姓    ",
		"Chinese Name": "  中文名字  ",
		"School Location": "学校位置",
		"Barcode": "条码号",
		"Old Student ID": "旧学号",
		"Date of Birth": "生日",
		"Age": "年龄",
		"Gender": "性别",
		"Parent Name": "家长姓名",
		"Home Phone": "家庭电话",
		"Cell Phone": "手机",
		"Cell Phone 2": "手机 2",
		"Pick up Person": "学生接人",
		"Address": "住址",
		"State": "州",
		"City": "城市",
		"Zipcode": "邮政编码",
		"Weekday/Weekend": "平日/周末",
		"Tuition Paid Day": "支付学费日期",
		"Payment Method": "付款方式",
		"Tuition Pay Amount": "总学费金额",
		"E-mail": "电子邮件",
		"Service Type": "课程级别",
		"Classes Awarded": "学生课程总数",
		"Classes Remaining": "剩下的课程",
		"Date": "日期",
		"Check-In Time": "到达时间",
		"Class Time": "上课时间",
		"How did you hear about the school?": "你是怎么找到我们学校?",
		"Notes": "记录",
		"No student": "\n找不到的学生 ！\n键入正确的名称或与系统管理员联系。\n",
		"Con student": "\n你確定想添加這個學生？",
		"Ase student": "\n一个学生用相同的条码。\n如果想添加这个学生,你要覆盖旧的学生?\n",
		"Sa student": "\n学生已被添加到数据库中",
		"Cs student": "\n你想要记录这个学生？\n",
		"No classes": "\n这名学生没有课程",
		"ok": "    确认    ",
		"yes": "    确认    ",
		"no": "    拒绝    ",
		"changelanguage": "English Language Display",
		"awardclass": "奖类",
		"awardoneclass": "添加一课 (+1)",
		"awardaddclass": "奖其他类",
		"browse": "浏览",
		"browsephoto": "浏览照片",
		"addstudent": "新增学生资料",
		"Add Students": "添加新学生", #students* for buttons
		"Scan Students": "扫描学生卡",
		"Save": "保存",
		"Student Database": "学生资料数据库",
		"Tools": "数据库管理",
		"Back to Main Menu": "返回到主菜单",
		"Exit": "退出",
		"Next": "下一次",
		"Back": "返回",
		"Search": "搜索学生",
		"Search By": "搜索方式",
		"cinstudent": "记录学生卡",
		"savestudent": "保存学生资料",
		"Database succesfully updated!": "数据库成功更新 ！\n",
		"File could not be imported": "不能导入文件\n",
		"Cancel": "取消",
		"Please choose a file": "\n请选择一个文件",
		"impdb": "导入数据库",
		"expdb": "导出数据库",
		"impxls": "从 Excel 中导入",
		"impt": "导入时间数据",
		"imptxls": "从 Excel 导入时间数据",
		"expxls": "导出到 excel 中",
		"curfile": "当前数据库文件",
		"choosedb": "选择数据库",
		"": "",
		"Classes remaining for this student": "学生剩余的课程",
		"spec": "",
		"gold60": "黄金 (+60)",
		"basic15": "基本 (+15)",
		"Ret to Main": "返回到软件而不保存吗？",
		"Scan": "Scan",
		"Manual": "Manual",
		"Con S student": "确实要将此学生的信息保存到数据库吗？",
		"close": "关闭",
		"Amount Owed": "所欠学费数额",
		">> Next 30 >>": "下一个",
		"<< Previous 30 <<": "上一页",
		">>> Last Page >>>": "最后一页",
		"Import succesful": "导入成功\n",
		"Students imported: ": "导入的学生: ",
		"Attendance data imported: ": "导入考勤: ",
		"Student information": "学生资料",
		"Address information": "地址",
		"Contact information": "联络",
		"Payment information": "付款资料",
		"Class time": "上课时间",
		"Renew classes": "添加课程",
		"Membership Expired": "会员已过期",
		"Number of classes": "添加课程",
		"Card Printed": "已打印卡",
		"Already Paid": "已支付学费",
		"Phone Number": "电话号码",
		"RYB Student Management" : "红黄蓝学生记录软件",
		"print report": "制作学生出席报告",
		"sdate": "Search Date",
		"Select Folder": "Select Folder",
		"filepath": "File Path",
		"Cash": "Cash",
		"Check": "Check",
		"Check Number": "Check Number",
		"Add Payment": "Add Payment",
		"Phone Number": "Phone Number",
		"RYB Student Management" : "RYB Student Management",
		"print report": "Print Report",
		"sdate": "Search Date",
		"Select Folder": "Select Folder",
		"salrep": "Salary Report",
		"print to file": "Make Report",
		"today's date": "Today's date",
		"last payment": "Last Payment",
		"dollar per hour": "Dollars per hour",
		"Hour": "Hour",
		"Minute": "Minute",
		"AM/PM": "AM/PM",
		"Print All": "Print All",
		"Confirm Time": "Confirm Time",
		"Confirm": "Confirm",
		"25s": " 25s",
		"50s": " 50s",
		"100s": " 100s",
		"set": "Set",
		"reset": "Reset",
		"resetcheckin": "Reset Check-In",
		"Confirm Reset": "Confirm Reset",
		"Early Check-ins have been reset": "Early Check-ins have been reset",
		"Yes, use current time": "Yes, use current time",
		"Yes, enter time": "Yes, enter time",
		"Brooklyn": "Brooklyn",
		"Chinatown": "Chinatown",
		"Elmhurst": "Elmhurst",
		"Flushing": "Flushing",
		"Choose School": "Choose School",
		"Print Successful": "Print Successful",
		"Early Check-in": "Early Check-in",
		"max hours": "Maximum Hours",
		"Choose PW File": "Choose PW File",
		"Create PW File": "Create PW File",
		"Create new Database": "Create new Database",
		"Convert to Encrypted DB": "Convert to Encrypted DB",
		"no_pw_set_pw": "Password must be reset.\nPlease enter the old password\nfollowed by the new password",
		"Enter Password": "Enter Password",
		"Reset DB Manager PW": "Reset DB Manager PW",
		"confirmed reset": "Password has been reset!",
		"wrong password try again": "You have entered the wrong password, try again!",
		"Choose Maker File": "Choose Maker File",
		"Create new Markerfile": "Create new Markerfile",
		"Database Backup Successful": "Database Backup Successful",
		"Student Information": "Student Information",
		"Attendance Table": "Attendance Table"
		}
		
}